### ISSUE TITLE
no 'FAINT_FILTERS' directory

### ISSUE THREAD

**Issue by spy653** [salman-abedin/faint#1]
1) `/usr/local/bin/faint: 45: cannot create ~/.local/share/faint/FAINT_FILTERS: Directory nonexistent`
2) `/usr/local/bin/faint-list: 36: cannot open ~/.local/share/faint/FAINT_FILTERS: No such file`

made sure I got the dependencies, installed, ran, none of the binds work and when I press enter on any file or directory I get this. Any ideas?

Ubuntu 20.04

**Comment by NICHOLAS85** [comment]
Try replacing the `~` at this line:https://github.com/salman-abedin/faint/blob/9772562a94e5bcfc492ea106dec06b45f9fc7f2d/src/faint#L20
with `$HOME`

**Comment by spy653** [comment]
Fixes the issue, none of the binds work but that's another issue.

**Comment by NICHOLAS85** [comment]
To fix keybinds change this line:
https://github.com/salman-abedin/faint/blob/9772562a94e5bcfc492ea106dec06b45f9fc7f2d/src/faint#L35
to `export FZF_DEFAULT_OPTS`, it's missing the s

**Comment by salman-abedin** [comment]
My bad guys! Thanks for pointing these out @NICHOLAS85.
