### ISSUE TITLE
faint image viewer

### ISSUE THREAD

**Issue by mrneilypops** [salman-abedin/faint#7]
How do I get to view an image in faint?
I get;
`/usr/local/bin/faint:   77:   : Permission denied`

**Comment by salman-abedin** [comment]
If you are not doing anything complex, just writing a one liner like `png|jpeg|jpg:feh;` on your `LAUNCH_CMDS` variable of your `faint-config` should do the trick where `feh` is the name of the program you would want to use.  
Don't forget to let me know whether everything went well or not.

**Comment by mrneilypops** [comment]
Works perfectly. Thanks.

**Comment by salman-abedin** [comment]
great.
