### ISSUE TITLE
How to add image viewer with latest version?

### ISSUE THREAD

**Issue by mrneilypops** [salman-abedin/faint#8]
In previous version I was using the one liner; `png|jpeg|jpg:feh;`
How do I add this to the new version?

**Comment by salman-abedin** [comment]
It's still a one liner.
```sh
png|jpg|jpeg) feh "$1";; 
```
or better yet...
```sh
png|jpg|jpeg) fork feh "$1";; 
```

**Comment by mrneilypops** [comment]
Got it thanks!
