### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by orhun** [salman-abedin/faint#9]
Hey,
I'm maintaining the `faint` project in Arch User Repository.
* [faint](https://aur.archlinux.org/packages/faint/) (builds from source)
* [faint-git](https://aur.archlinux.org/packages/faint-git/) (VCS/development package)

Unfortunately I set its license to `unknown`. Are you planning to add an open source license to the project soon?

**Comment by salman-abedin** [comment]
Wow. I really appreciate the effort man!  
The funny thing is I did add a license but deleted it by mistake. 😅  
Fixing it right away.
